name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  default:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo "default"

  always:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - run: echo "always"
        if: success()

  failure:
    runs-on: ubuntu-latest
    needs: [build]
    if: failure()
    steps:
      - run: echo "failure"

  success:
    runs-on: ubuntu-latest
    needs: [build]
    if: success()
    steps:
      - run: echo "success"

  cancelled:
    runs-on: ubuntu-latest
    needs: [success]
    if: cancelled()
    steps:
      - run: echo "cancelled"
