name: CI

on: [push]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: echo "prepare"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "test"
      - uses: ZauberNerd/act-test/.github/actions/test@pre-post-test
        with:
          numOctocats: "2"
      - run: echo "after test"
