name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  always:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - run: echo "needs.build.result => '${{ needs.build.result }}' '${{ needs.build.result == 'failure' }}'"
      - run: echo "${{ toJSON(needs.build) }}"
      - run: echo "always"
        if: needs.build.result == 'success'

  failure:
    runs-on: ubuntu-latest
    needs: [build]
    if: needs.build.result == 'failure'
    steps:
      - run: echo "failure"

  success:
    runs-on: ubuntu-latest
    needs: [build]
    if: needs.build.result == 'success'
    steps:
      - run: echo "success"
