name: CI

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "before"
      - uses: ./.github/actions/pre-post
      - run: echo "after"
