name: issue-597
on: push
  

jobs:
  my_first_job:
    
    runs-on: ubuntu-latest
    steps:
      - name: My first false step
        if: endsWith('Should not', 'o1')
        uses: ZauberNerd/act-test@pre-post
        with:
          ref: refs/pull/${{github.event.pull_request.number}}/merge
      - name: My first true step
        if: endsWith('Hello world', 'ld')
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Renst the Octocat"
      - name: My second false step
        if: endsWith('Should not evaluate', 'o2')
        uses: ZauberNerd/act-test@pre-post
        with:
          ref: refs/pull/${{github.event.pull_request.number}}/merge
      - name: My third false step
        if: ${{endsWith('Should not evaluate', 'o3')}}
        uses: ZauberNerd/act-test@pre-post
        with:
          ref: refs/pull/${{github.event.pull_request.number}}/merge
