name: CI

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "before"
      - uses: ZauberNerd/act-test@pre-post
        if: failure()
      - run: echo "after"
      # - run: exit 1
      # - run: echo "failed stp"
      #   if: failure()
