name: CI

on: [push]

jobs:
  contexts:
    runs-on: ubuntu-latest
    steps:
      - id: succeeds
        run: echo "success"
      - id: continues
        continue-on-error: true
        run: echo "continue" && exit 1
      - id: steps-context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
