name: issue-597
on: push
  

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - id: second
        uses: ZauberNerd/act-test@pre-post
        env:
          myNull: ${{ null }}
          myBoolean: ${{ false }}
          myIntegerNumber: ${{ 711 }}
          myFloatNumber: ${{ -9.2 }}
          myHexNumber: ${{ 0xff }}
          myExponentialNumber: ${{ -2.99e-2 }}
          myString: ${{ 'Mona the Octocat' }}
          myEscapedString: ${{ 'It''s open source!' }}
          comparison: ${{ fromJSON('"foo"') == 'FOO' }} # broken, but too much work
          objectFilters: ${{ join(fromJSON('[{"name":"apple"},{"name":"orange"}]').*.name, ',') }} # broken
          myPr: a${{ github.pull_request.abc.def }}b # should not error
          startsWith: a${{ join(fromJSON('[0,1]'), github.pull_request.abc.def) }}b # should join 'a01b'
          formatted: ${{ format('{{Hello {0} {1} {2}!}}', 'Mona', 'the', github.pull_request.abc.def) }} # broken
