name: expressions
on: push
env:
  TRUE: "true"
  FALSE: "false"
  EMPTY: ""  

jobs:
  ifs:
    runs-on: self-hosted
    steps:
      - name: "Test if: true"
        if: true
        run: |
          echo "if: true"

      - name: "Test if: null"
        if: null
        run: |
          echo "if: null"

      - name: "Test if: 0"
        if: 0
        run: |
          exit 1

      - name: "Test if: 3"
        if: 3
        run: |
          echo "if: 3"

      - name: "Test if: ''"
        if: ''
        run: |
          echo "if: ''"

      # Note: GH tries to evaluate "if: 'abc' as context abc"
      # - name: "Test if: 'abc'"
      #   if: 'abc'
      #   run: |
      #     echo "if: 'abc'"
      - name: "Test if: github.job"
        if: github.job
        run: |
          echo "if: github.job"

      - name: "Test if: github.empty_str"
        if: github.empty_str
        run: |
          exit 1

      - name: "Test if: env.TRUE"
        if: env.TRUE
        run: |
          exit 1

      - name: "Test if: env.FALSE"
        if: env.FALSE
        run: |
          exit 1

      - name: "Test if: env.EMPTY"
        if: env.EMPTY
        run: |
          exit 1

      - name: "Test if: fromJSON"
        if: fromJSON('{"a":1}')
        run: |
          echo "if: fromJSON"

      - name: "Test if: 1 && true"
        if: 1 && true
        run: |
          echo "if: 1 && true"

      - name: "Test if: 0 || NaN"
        if: 0 || NaN
        run: |
          exit 1

      - name: "Test if: true || null"
        if: true || null
        run: |
          echo "if: true || null"

      - name: "Test if: null || true"
        if: null || true
        run: |
          echo "if: null || true"


      - name: "Test if: 0 || null"
        if: ${{ 0 || null }}
        run: |
          echo "if: 0 || null"

      - name: "Test if: true"
        if: ${{ true }}
        run: |
          echo "if: true"

      - name: "Test if: null"
        if: ${{ null }}
        run: |
          echo "if: null"

      - name: "Test if: 0"
        if: ${{ 0 }}
        run: |
          exit 1

      - name: "Test if: 3"
        if: ${{ 3 }}
        run: |
          echo "if: 3"

      - name: "Test if: ''"
        if: ${{ '' }}
        run: |
          echo "if: ''"

      # Note: GH tries to evaluate "if: 'abc' as context abc"
      # - name: "Test if: 'abc'"
      #   if: 'abc'
      #   run: |
      #     echo "if: 'abc'"
      - name: "Test if: github.job"
        if: ${{ github.job }}
        run: |
          echo "if: github.job"

      - name: "Test if: env.TRUE"
        if: ${{ env.TRUE }}
        run: |
          exit 1

      - name: "Test if: env.FALSE"
        if: ${{ env.FALSE }}
        run: |
          exit 1

      - name: "Test if: env.EMPTY"
        if: ${{ env.EMPTY }}
        run: |
          exit 1

      - name: "Test if: fromJSON"
        if: ${{ fromJSON('{"a":1}') }}
        run: |
          echo "if: fromJSON"

      - name: "Test if: 1 && true"
        if: ${{ 1 && true }}
        run: |
          echo "if: 1 && true"

      - name: "Test if: 0 || NaN"
        if: ${{ 0 || NaN }}
        run: |
          exit 1

      - name: "Test if: 0 || null"
        if: ${{ 0 || null }}
        run: |
          echo "if: 0 || null"
