name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          [ "${{ join('str','octocat') }}" == "hello" ]
        continue-on-error: true
      - run: |
          [ "${{ join(1,'octocat') }}" == "hello" ]
        continue-on-error: true

